# Keys
KEY_FATIGUE_ERRORS = "fatigueErrors"
KEY_EQUIPMENT_ERRORS = "equipmentErrors"
KEY_OPERATIONS = "operations"
KEY_OPERATION_TYPE = "opType"
KEY_END_TIME = "endTime"
KEY_ERROR_RECORDS = "errorRecords"
KEY_FATIGUE_ERROR_COUNT = "fatigueErrorCount"
KEY_EQUIPMENT_ERROR_COUNT = "equipmentErrorCount"
KEY_EQUIPMENT_REQUESTED =  "requested"
KEY_EQUIPMENT_PRESENT = "present"
KEY_EQUIPMENT_LOCKED = "locked"