# Keys
KEY_FATIGUE_LOG = "fatigueLog"
KEY_OPERATIONS = "operations"
KEY_OPERATION_TYPE = "opType"
KEY_END_TIME = "endTime"
KEY_ERROR_RECORDS = "errorRecords"
KEY_FATIGUE_RATE = "fatigueRate"
KEY_EQUIPMENT_RATE = "equipmentRate"
KEY_EQUIPMENT_REQUESTED =  "requested"
KEY_EQUIPMENT_PRESENT = "present"
KEY_EQUIPMENT_LOCKED = "locked"